plugins:
  - jekyll-seo-tag


description: Amanda Pell is a pottery artist who designs and makes pottery in Lincolnshire near Spalding. She makes a range of slab built pots house signs and have lots of ways to personalise some of my own designs by adding birth or wedding details.

author: Amanda Pell


# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
